### ISSUE TITLE
Presentation 1st of March

### ISSUE THREAD

**Issue by Foxboron** [svimanet/INFO216#3]
- [ ] what do you want to make? - or: what is your application going to do? #6
- [ ] which datasets are you going to use? - or: where are you going to get your data from? are you using (only) semantic data, or will you need to lift (some of) them?
- [ ] which vocabularies are you going to use? 
  - [ ] do you think you will need to create e new vocabulary/ontology, or extend existing ones?
- [ ] why is it a good idea to do this using semantic technologies? - or: what does your app do that was not possible (or at least not easy) to do before?
- [ ] what have you done so far (see below)?
- [ ] what are you planning to do in the next four weeks? #4 
- [ ] have you got particular problems you need to address? See #6
